apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pe7bsg8bb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pe7bsg8bb-go 
  name: pe7bsg8bb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pe7bsg8bb-go 
